import React from 'react';
import html2canvas from 'html2canvas';
import toast from 'react-hot-toast';
import { ShareIcon, ArrowDownTrayIcon, XMarkIcon, TrophyIcon } from '@heroicons/react/24/outline';

export default function WinnerPoster({ winner, prizeAmount, cycleLabel, groupName, onClose }) {
  if (!winner) return null;
  const winnerName = winner.member?.name || winner.name || 'Winner';
  
  const downloadPoster = async () => {
    const el = document.getElementById('winner-poster-capture');
    if (!el) return;
    try {
      const canvas = await html2canvas(el, { 
        backgroundColor: '#ffffff', 
        scale: 3, // High quality
      });
      const imgData = canvas.toDataURL('image/png');
      const a = document.createElement('a'); 
      a.href = imgData; 
      a.download = `Winner-${winnerName.replace(/\s+/g, '-')}-${cycleLabel.replace(/\s+/g, '-')}.png`;
      document.body.appendChild(a); 
      a.click(); 
      document.body.removeChild(a);
      toast.success('Poster downloaded!');
    } catch(err) { 
      toast.error('Download failed'); 
    }
  };

  const sharePoster = async () => {
    const el = document.getElementById('winner-poster-capture');
    if (!el) return;
    try {
      const canvas = await html2canvas(el, { 
        backgroundColor: '#ffffff', 
        scale: 2,
      });
      canvas.toBlob(async (blob) => {
        const file = new File([blob], 'winner.png', { type: 'image/png' });
        if (navigator.share) {
          await navigator.share({ 
            files: [file], 
            title: 'ChitFund Winner', 
            text: `Congratulations to ${winnerName} for winning ₹${Number(prizeAmount).toLocaleString()} in ${groupName}!` 
          });
        } else { 
          toast.error('Sharing not supported on this device'); 
        }
      });
    } catch(err) {
      toast.error('Sharing failed');
    }
  };

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-slate-900/80 backdrop-blur-sm z-[999999] p-4">
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm overflow-hidden flex flex-col animate-scale-in">
        
       {/* Poster Capture Area */}
        <div id="winner-poster-capture" className="bg-gradient-to-b from-brand-50 to-white pt-10 pb-12 px-8 text-center relative overflow-hidden">
           {/* Decorative elements */}
           <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-gold-400 via-amber-500 to-gold-400"></div>
           <div className="absolute -top-10 -right-10 w-32 h-32 bg-gold-400/10 rounded-full blur-2xl"></div>
           <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-brand-400/10 rounded-full blur-2xl"></div>

           <div className="w-20 h-20 bg-gradient-to-br from-gold-400 to-amber-600 rounded-full flex items-center justify-center shadow-glow-gold mx-auto mb-6">
             <TrophyIcon className="w-10 h-10 text-white" />
           </div>

           <h1 className="text-xl font-black text-slate-800 tracking-widest uppercase mb-1">Congratulations</h1>
           
           <h2 className="text-4xl font-black text-brand-700 bg-clip-text mb-2 tracking-tight">
             {winnerName}
           </h2>

           <div className="inline-block bg-brand-100 text-brand-800 px-4 py-1.5 rounded-full text-sm font-bold tracking-widest uppercase mb-6">
             {cycleLabel}
           </div>

           <p className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-1">Prize Amount</p>
           <h3 className="text-5xl font-black text-emerald-600 drop-shadow-sm mb-6">
             ₹{Number(prizeAmount).toLocaleString()}
           </h3>

           {groupName && (
             <div className="border-t border-slate-200 pt-4 mt-2">
               <p className="text-xs text-slate-400 uppercase tracking-widest font-bold">Group</p>
               <p className="text-sm font-black text-slate-700">{groupName}</p>
             </div>
           )}

           <div className="mt-4 text-[10px] text-slate-300 font-bold tracking-widest uppercase">
             Generated by ChitFund Pro
           </div>
        </div>

        {/* Controls (Not included in capture) */}
        <div className="bg-slate-50 border-t border-slate-100 p-4 shrink-0 flex gap-2 justify-center">
           <button 
             onClick={downloadPoster} 
             className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-slate-900 hover:bg-black text-white rounded-xl font-bold text-sm transition-colors"
           >
             <ArrowDownTrayIcon className="w-5 h-5" /> Download
           </button>
           <button 
             onClick={sharePoster} 
             className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-brand-600 hover:bg-brand-700 text-white rounded-xl font-bold text-sm transition-colors"
           >
             <ShareIcon className="w-5 h-5" /> Share
           </button>
           <button 
             onClick={onClose} 
             className="w-12 flex shrink-0 items-center justify-center px-0 py-3 bg-slate-200 hover:bg-slate-300 text-slate-700 rounded-xl font-bold transition-colors"
             title="Close"
           >
             <XMarkIcon className="w-5 h-5" />
           </button>
        </div>

      </div>
    </div>
  );
}
